spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 1d
      use-key-prefix: true
  datasource:
    url: jdbc:postgresql://localhost:5433/downloader
    username: postgres
  data:
    redis:
      host: localhost
      port: 6380
      password:
      database: 0
springdoc:
  swagger-ui:
    syntax-highlight:
      activated: false
    operations-sorter: method
    tags-sorter: alpha
  override-with-generic-response: false
  writer-with-order-by-keys: true
  show-actuator: true